apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-klage
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  ingresses:
    - https://familie-klage-backend.intern.dev.nav.no
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
      cpu: 200m
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_14 # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        tier: db-f1-micro
        diskAutoresize: true
        cascadingDelete: false
        highAvailability: false
        pointInTimeRecovery: true
        maintenance:
          day: 7
          hour: 23
        databases:
          - name: familie-klage
            envVarPrefix: DB
  accessPolicy:
    inbound:
      rules:
        - application: familie-klage-frontend
        - application: familie-klage-frontend-lokal
        - application: familie-ef-sak
        - application: familie-ks-sak
        - application: familie-ba-sak
        - application: familie-prosessering
        - application: familie-prosessering-lokal
    outbound:
      rules:
        - application: familie-ef-sak
        - application: familie-ks-sak
        - application: familie-ba-sak
        - application: familie-ef-proxy
          cluster: dev-fss
        - application: familie-tilbake
        - application: familie-brev
        - application: familie-dokument
        - application: kabal-api
          namespace: klage
        - application: repr-api
          namespace: repr
        - application: logging
          namespace: nais-system
      external:
        - host: api-gw-q1.oera.no
        - host: teamfamilie-unleash-api.nav.cloud.nais.io
        - host: familie-oppdrag.dev-fss-pub.nais.io
        - host: familie-integrasjoner.dev-fss-pub.nais.io
        - host: familie-ef-infotrygd.dev-fss-pub.nais.io
        - host: familie-ef-proxy.dev-fss-pub.nais.io
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      claims:
        groups:
          - id: d21e00a4-969d-4b28-8782-dc818abfae65 # 0000-GA-Barnetrygd
          - id: 9449c153-5a1e-44a7-84c6-7cc7a8867233 # 0000-GA-Barnetrygd-Beslutter
          - id: 93a26831-9866-4410-927b-74ff51a9107c # 0000-GA-Barnetrygd-Veileder
          - id: ee5e0b5e-454c-4612-b931-1fe363df7c2c # 0000-GA-Enslig-Forsorger-Saksbehandler
          - id: 01166863-22f1-4e16-9785-d7a05a22df74 # 0000-GA-Enslig-Forsorger-Beslutter
          - id: 19dcbfde-4cdb-4c64-a1ea-ac9802b03339 # 0000-GA-Enslig-Forsorger-Veileder
          - id: c7e0b108-7ae6-432c-9ab4-946174c240c0 # 0000-GA-Kontantstotte     (saksbehandler)
          - id: 52fe1bef-224f-49df-a40a-29f92d4520f8 # 0000-GA-Kontantstotte-Beslutter
          - id: 71f503a2-c28f-4394-a05a-8da263ceca4a # 0000-GA-Kontantstotte-Veileder
          - id: 928636f4-fd0d-4149-978e-a6fb68bb19de # 0000-GA-STDAPPS - tilgang til prosessering
          - id: dbe4ad45-320b-4e9a-aaa1-73cca4ee124d # 0000-GA-Egne_ansatte
        extra:
          - "NAVident"
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
  envFrom:
    - secret: familie-klage-unleash-api-token
