apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-klage
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  ingresses:
    - https://familie-klage-backend.intern.nav.no
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: 2048Mi
    requests:
      memory: 512Mi
      cpu: 200m
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  gcp:
    sqlInstances:
      - type: POSTGRES_14 # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        tier: db-custom-1-3840
        diskAutoresize: true
        cascadingDelete: false
        highAvailability: true
        pointInTimeRecovery: true
        maintenance:
          day: 7
          hour: 23
        databases:
          - name: familie-klage
            envVarPrefix: DB
  accessPolicy:
    inbound:
      rules:
        - application: familie-klage-frontend
        - application: familie-ef-sak
        - application: familie-ks-sak
        - application: familie-ba-sak
        - application: familie-prosessering
    outbound:
      rules:
        - application: familie-tilbake
        - application: familie-ef-sak
        - application: familie-ks-sak
        - application: familie-ba-sak
        - application: familie-ef-proxy
          cluster: prod-fss
        - application: familie-brev
        - application: familie-dokument
        - application: kabal-api
          namespace: klage
        - application: repr-api
          namespace: repr
      external:
        - host: api-gw.oera.no
        - host: teamfamilie-unleash-api.nav.cloud.nais.io
        - host: familie-oppdrag.prod-fss-pub.nais.io
        - host: familie-integrasjoner.prod-fss-pub.nais.io
        - host: familie-ef-infotrygd.prod-fss-pub.nais.io
        - host: familie-ef-proxy.prod-fss-pub.nais.io
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        groups:
          - id: 847e3d72-9dc1-41c3-80ff-f5d4acdd5d46 # 0000-GA-Barnetrygd
          - id: 7a271f87-39fb-468b-a9ee-6cf3c070f548 # 0000-GA-Barnetrygd-Beslutter
          - id: 199c2b39-e535-4ae8-ac59-8ccbee7991ae # 0000-GA-Barnetrygd-Veileder
          - id: 6406aba2-b930-41d3-a85b-dd13731bc974 # 0000-GA-Enslig-Forsorger-Saksbehandler
          - id: 5fcc0e1d-a4c2-49f0-93dc-27c9fea41e54 # 0000-GA-Enslig-Forsorger-Beslutter
          - id: 31778fd8-3b71-4867-8db6-a81235fbe001 # 0000-GA-Enslig-Forsorger-Veileder
          - id: e40090eb-c2fb-400e-b412-e9084019a73b # 0000-GA-Kontantstotte
          - id: 4e7f23d9-5db1-45c0-acec-89c86a9ec678 # 0000-GA-Kontantstotte-Beslutter
          - id: 54cd86b8-2e23-48b2-8852-b05b5827bb0f # 0000-GA-Kontantstotte-Veileder
          - id: 87190cf3-b278-457d-8ab7-1a5c55a9edd7 # Group_87190cf3-b278-457d-8ab7-1a5c55a9edd7 tilgang til prosessering
          - id: e750ceb5-b70b-4d94-b4fa-9d22467b786b # 0000-GA-Egne_ansatte

        extra:
          - "NAVident"
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
  envFrom:
    - secret: familie-klage-unleash-api-token