application:
  name: familie-klage
server:
  servlet:
    context-path: /
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

springdoc:
  packagesToScan: no.nav.familie.klage
  pathsToMatch: /v3/api-docs,/api/**
  swagger-ui:
    disable-swagger-default-url: true

no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
    accepted_audience: ${AZURE_APP_CLIENT_ID}
    cookie_name: azure_token
  client:
    registration:
      familie-integrasjoner:
        resource-url: ${FAMILIE_INTEGRASJONER_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${FAMILIE_INTEGRASJONER_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      familie-integrasjoner-clientcredentials:
        resource-url: ${FAMILIE_INTEGRASJONER_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: client_credentials
        scope: ${FAMILIE_INTEGRASJONER_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      pdl:
        resource-url: ${PDL_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${PDL_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      pdl-clientcredentials:
        resource-url: ${PDL_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: client_credentials
        scope: ${PDL_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      kabal:
        resource-url: ${KABAL_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${KABAL_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      kabal-clientcredentials:
        resource-url: ${KABAL_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: client_credentials
        scope: ${KABAL_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      familie-ef-sak:
        resource-url: ${FAMILIE_EF_SAK_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${FAMILIE_EF_SAK_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      familie-ef-sak-clientcredentials:
        resource-url: ${FAMILIE_EF_SAK_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: client_credentials
        scope: ${FAMILIE_EF_SAK_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      ef-proxy:
        resource-url: ${FAMILIE_EF_PROXY_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: client_credentials
        scope: ${FAMILIE_EF_PROXY_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      familie-ks-sak:
        resource-url: ${FAMILIE_KS_SAK_URL}
        token-endpoint-url: ${AZUREAD_TOKEN_ENDPOINT_URL}
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${FAMILIE_KS_SAK_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic




PDL_SCOPE: api://${DEPLOY_ENV}-fss.pdl.pdl-api/.default
KABAL_SCOPE: api://${DEPLOY_ENV}-gcp.klage.kabal-api/.default
FAMILIE_EF_SAK_SCOPE: api://${DEPLOY_ENV}-gcp.teamfamilie.familie-ef-sak/.default
FAMILIE_EF_PROXY_SCOPE: api://${DEPLOY_ENV}-fss.teamfamilie.familie-ef-proxy/.default
FAMILIE_KS_SAK_SCOPE: api://${DEPLOY_ENV}-gcp.teamfamilie.familie-ks-sak/.default


spring:
  mvc:
    format:
      date: iso
      date-time: iso
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  data:
    jdbc:
      repositories:
        enabled: true
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
  flyway:
    enabled: true
    placeholders:
      ignoreIfProd:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/familie-klage
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      connection-test-query: "select 1"
      max-lifetime: 30000
      minimum-idle: 1
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      security:
        protocol: SSL
      ssl:
        keystore:
          type: PKCS12
          location: ${KAFKA_KEYSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        truststore:
          type: PKCS12
          location: ${KAFKA_TRUSTSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
    producer:
      acks: all
    consumer:
      group-id: familie-klage
      max-poll-records: 1
      auto-offset-reset: latest
      enable-auto-commit: false
management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
    path-mapping:
      info: "status/isAlive"
  metrics.export.prometheus.enabled: true
  metrics.web.server.auto-time-requests: true

DEPLOY_ENV: prod
ON_PREM_URL_ENV: prod

AZUREAD_TOKEN_ENDPOINT_URL: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token

FAMILIE_BREV_API_URL: http://familie-brev
FAMILIE_DOKUMENT_URL: http://familie-dokument

FAMILIE_INTEGRASJONER_URL: https://familie-integrasjoner.${ON_PREM_URL_ENV}-fss-pub.nais.io
PDL_URL: https://pdl-api.${ON_PREM_URL_ENV}-fss-pub.nais.io

KABAL_URL: https://kabal-api.intern.nav.no

FAMILIE_EF_SAK_URL: http://familie-ef-sak

FAMILIE_EF_PROXY_URL: https://familie-ef-proxy.${ON_PREM_URL_ENV}-fss-pub.nais.io

FAMILIE_KS_SAK_URL: http://familie-ks-sak

FAMILIE_BLANKETT_API_URL: http://familie-ef-blankett

rolle:
  ba:
    saksbehandler: "847e3d72-9dc1-41c3-80ff-f5d4acdd5d46"
    beslutter: "7a271f87-39fb-468b-a9ee-6cf3c070f548"
    veileder: "199c2b39-e535-4ae8-ac59-8ccbee7991ae"
  ef:
    saksbehandler: "6406aba2-b930-41d3-a85b-dd13731bc974"
    beslutter: "5fcc0e1d-a4c2-49f0-93dc-27c9fea41e54"
    veileder: "31778fd8-3b71-4867-8db6-a81235fbe001"
  ks:
    saksbehandler: "e40090eb-c2fb-400e-b412-e9084019a73b"
    beslutter: "4e7f23d9-5db1-45c0-acec-89c86a9ec678"
    veileder: "54cd86b8-2e23-48b2-8852-b05b5827bb0f"


funksjonsbrytere:
  enabled: true
  unleash:
    uri: https://unleash.nais.io/api/
    environment: ${NAIS_CLUSTER_NAME}
    applicationName: ${NAIS_APP_NAME}

prosessering:
  continuousRunning.enabled: true
  fixedDelayString:
    in:
      milliseconds: 15000
  delete:
    after:
      weeks: 16

lenker:
  EF_SAK_FRONTEND_URL: "https://ensligmorellerfar.intern.nav.no/ekstern"
  BA_SAK_FRONTEND_URL: "https://barnetrygd.intern.nav.no"

BEHANDLINGSSTATISTIKK_TOPIC: teamfamilie.aapen-klage-behandlingsstatistikk