package no.nav.familie.klage.brev.dto

enum class FritekstBrevtype {
    SANKSJON,
    VEDTAK_INVILGELSE,
    VEDTAK_AVSLAG,
    VEDTAK_OPPHØR,
    VEDTAK_REVURDERING,
    VEDTAK_INNVILGELSE_BARNETILSYN,
    VEDTAK_AVSLAG_BARNETILSYN,
    VEDTAK_INNVILGELSE_SKOLEPENGER,
    VEDTAK_AVSLAG_SKOLEPENGER
}
