#######
# Denne er brukt til å gjøre det mulig å bruke tokens lokalt
#
# secret kan hentes fra cluster med "kubectl -n teamfamilie get secret azuread-familie-klage-lokal -o json | jq '.data | map_values(@base64d)'"
#
# Kjøres en gang eller ved endringer med
# kubectl apply -f .deploy/azure-ad-app-lokal.yaml
###
apiVersion: nais.io/v1
kind: AzureAdApplication
metadata:
  name: familie-klage-lokal
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  preAuthorizedApplications:
    - application: familie-klage-frontend-lokal
      cluster: dev-gcp
      namespace: teamfamilie
    - application: familie-prosessering-lokal
      cluster: dev-gcp
      namespace: teamfamilie
    - application: familie-ef-sak-lokal
      cluster: dev-gcp
      namespace: teamfamilie
  tenant: trygdeetaten.no
  secretName: azuread-familie-klage-lokal
  claims:
    groups:
      - id: d21e00a4-969d-4b28-8782-dc818abfae65 # 0000-GA-Barnetrygd
      - id: 9449c153-5a1e-44a7-84c6-7cc7a8867233 # 0000-GA-Barnetrygd-Beslutter
      - id: 93a26831-9866-4410-927b-74ff51a9107c # 0000-GA-Barnetrygd-Veileder
      - id: ee5e0b5e-454c-4612-b931-1fe363df7c2c # 0000-GA-Enslig-Forsorger-Saksbehandler
      - id: 01166863-22f1-4e16-9785-d7a05a22df74 # 0000-GA-Enslig-Forsorger-Beslutter
      - id: 19dcbfde-4cdb-4c64-a1ea-ac9802b03339 # 0000-GA-Enslig-Forsorger-Veileder
      - id: 71f503a2-c28f-4394-a05a-8da263ceca4a # 0000-GA-Kontantstotte-Veileder
      - id: c7e0b108-7ae6-432c-9ab4-946174c240c0 # 0000-GA-Kontantstotte     (saksbehandler)
      - id: 52fe1bef-224f-49df-a40a-29f92d4520f8 # 0000-GA-Kontantstotte-Beslutter
      - id: 928636f4-fd0d-4149-978e-a6fb68bb19de # 0000-GA-STDAPPS - tilgang til prosessering
    extra:
      - "NAVident"