apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-klage-behandlingsstatistikk
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 2160
  acl:
    - team: teamfamilie
      application: familie-famklage
      access: readwrite
    - team: ptsak
      application: pt-sak-famklage
      access: read