apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-klage-behandlingsstatistikk
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 720
  acl:
    - team: teamfamilie
      application: familie-klage
      access: readwrite
    - team: ptsak
      application: pt-sak-famklage-preprod
      access: read
    - team: ptsak
      application: pt-sak-famklage-dev
      access: read